// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthServiceI is an autogenerated mock type for the AuthServiceI type
type AuthServiceI struct {
	mock.Mock
}

// GenerateJwt provides a mock function with given fields: email
func (_m *AuthServiceI) GenerateJwt(email string) (string, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJwt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIsValid provides a mock function with given fields: tokenStr
func (_m *AuthServiceI) TokenIsValid(tokenStr string) bool {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for TokenIsValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(tokenStr)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewAuthServiceI creates a new instance of AuthServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceI {
	mock := &AuthServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
