// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	eventbus "github.com/vladovsiychuk/microservice-demo-go/pkg/event-bus"
)

// EventBusI is an autogenerated mock type for the EventBusI type
type EventBusI struct {
	mock.Mock
}

// Publish provides a mock function with given fields: event
func (_m *EventBusI) Publish(event eventbus.Event) {
	_m.Called(event)
}

// NewEventBusI creates a new instance of EventBusI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBusI(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBusI {
	mock := &EventBusI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
