// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	rsa "crypto/rsa"

	mock "github.com/stretchr/testify/mock"
)

// KeysI is an autogenerated mock type for the KeysI type
type KeysI struct {
	mock.Mock
}

// GetPrivateKey provides a mock function with given fields:
func (_m *KeysI) GetPrivateKey() (*rsa.PrivateKey, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 *rsa.PrivateKey
	var r1 error
	if rf, ok := ret.Get(0).(func() (*rsa.PrivateKey, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *rsa.PrivateKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PrivateKey)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicKey provides a mock function with given fields:
func (_m *KeysI) GetPublicKey() (*rsa.PublicKey, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *rsa.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func() (*rsa.PublicKey, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *rsa.PublicKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rotate provides a mock function with given fields:
func (_m *KeysI) Rotate() {
	_m.Called()
}

// NewKeysI creates a new instance of KeysI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeysI(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeysI {
	mock := &KeysI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
