// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	post "github.com/vladovsiychuk/microservice-demo-go/internal/post"
)

// PostServiceI is an autogenerated mock type for the PostServiceI type
type PostServiceI struct {
	mock.Mock
}

// CreatePost provides a mock function with given fields: req
func (_m *PostServiceI) CreatePost(req post.PostRequest) (post.PostI, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 post.PostI
	var r1 error
	if rf, ok := ret.Get(0).(func(post.PostRequest) (post.PostI, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(post.PostRequest) post.PostI); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(post.PostI)
		}
	}

	if rf, ok := ret.Get(1).(func(post.PostRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: postId
func (_m *PostServiceI) FindById(postId uuid.UUID) (post.PostI, error) {
	ret := _m.Called(postId)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 post.PostI
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (post.PostI, error)); ok {
		return rf(postId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) post.PostI); ok {
		r0 = rf(postId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(post.PostI)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePost provides a mock function with given fields: postId, req
func (_m *PostServiceI) UpdatePost(postId uuid.UUID, req post.PostRequest) (post.PostI, error) {
	ret := _m.Called(postId, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 post.PostI
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, post.PostRequest) (post.PostI, error)); ok {
		return rf(postId, req)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, post.PostRequest) post.PostI); ok {
		r0 = rf(postId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(post.PostI)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, post.PostRequest) error); ok {
		r1 = rf(postId, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostServiceI creates a new instance of PostServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostServiceI {
	mock := &PostServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
