// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	post "github.com/vladovsiychuk/microservice-demo-go/internal/post"
)

// PostServiceInternalI is an autogenerated mock type for the PostServiceInternalI type
type PostServiceInternalI struct {
	mock.Mock
}

// CreatePost provides a mock function with given fields: req
func (_m *PostServiceInternalI) CreatePost(req post.PostRequest) (*post.Post, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(post.PostRequest) (*post.Post, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(post.PostRequest) *post.Post); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(post.PostRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePost provides a mock function with given fields: postId, req
func (_m *PostServiceInternalI) UpdatePost(postId uuid.UUID, req post.PostRequest) (*post.Post, error) {
	ret := _m.Called(postId, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, post.PostRequest) (*post.Post, error)); ok {
		return rf(postId, req)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, post.PostRequest) *post.Post); ok {
		r0 = rf(postId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, post.PostRequest) error); ok {
		r1 = rf(postId, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostServiceInternalI creates a new instance of PostServiceInternalI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostServiceInternalI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostServiceInternalI {
	mock := &PostServiceInternalI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
