// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backendforfrontend "github.com/vladovsiychuk/microservice-demo-go/internal/backendforfrontend"

	uuid "github.com/google/uuid"
)

// PostAggregateRepositoryI is an autogenerated mock type for the PostAggregateRepositoryI type
type PostAggregateRepositoryI struct {
	mock.Mock
}

// Create provides a mock function with given fields: post
func (_m *PostAggregateRepositoryI) Create(post backendforfrontend.PostAggregateI) error {
	ret := _m.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(backendforfrontend.PostAggregateI) error); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: postId
func (_m *PostAggregateRepositoryI) FindById(postId uuid.UUID) (backendforfrontend.PostAggregateI, error) {
	ret := _m.Called(postId)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 backendforfrontend.PostAggregateI
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (backendforfrontend.PostAggregateI, error)); ok {
		return rf(postId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) backendforfrontend.PostAggregateI); ok {
		r0 = rf(postId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backendforfrontend.PostAggregateI)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: post
func (_m *PostAggregateRepositoryI) Update(post backendforfrontend.PostAggregateI) error {
	ret := _m.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(backendforfrontend.PostAggregateI) error); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPostAggregateRepositoryI creates a new instance of PostAggregateRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostAggregateRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostAggregateRepositoryI {
	mock := &PostAggregateRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
