// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	post "github.com/vladovsiychuk/microservice-demo-go/internal/post"
)

// PostRepositoryI is an autogenerated mock type for the PostRepositoryI type
type PostRepositoryI struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *PostRepositoryI) Create(_a0 post.PostI) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(post.PostI) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: postId
func (_m *PostRepositoryI) FindById(postId uuid.UUID) (post.PostI, error) {
	ret := _m.Called(postId)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 post.PostI
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (post.PostI, error)); ok {
		return rf(postId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) post.PostI); ok {
		r0 = rf(postId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(post.PostI)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *PostRepositoryI) Update(_a0 post.PostI) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(post.PostI) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPostRepositoryI creates a new instance of PostRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostRepositoryI {
	mock := &PostRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
