// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SessionTokenRepositoryI is an autogenerated mock type for the SessionTokenRepositoryI type
type SessionTokenRepositoryI struct {
	mock.Mock
}

// NewSessionTokenRepositoryI creates a new instance of SessionTokenRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionTokenRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionTokenRepositoryI {
	mock := &SessionTokenRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
